x-base: &base
  restart: unless-stopped
  env_file: .env

services:
  api:
    <<: *base
    container_name: api_gateway
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: ["./main"]